import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Question from '../models/Question.model.js';

dotenv.config();

const MONGO_URI = process.env.MONGO_URI;

const mcqQuestions = 
[
    {
        class: 'Class 6',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'What is the value of 7 × 8?',
        options: ['54', '56', '64', '58'],
        correctAnswer: '56',
    },
    {
        class: 'Class 7',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'Which gas is essential for human respiration?',
        options: ['Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Hydrogen'],
        correctAnswer: 'Oxygen',
    },
    {
        class: 'Class 8',
        subject: 'English',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'Choose the correct antonym of “Generous”.',
        options: ['Kind', 'Selfish', 'Caring', 'Loving'],
        correctAnswer: 'Selfish',
    },
    {
        class: 'Class 9',
        subject: 'History',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'Who was the first President of independent India?',
        options: ['Dr. Rajendra Prasad', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel'],
        correctAnswer: 'Dr. Rajendra Prasad',
    },
    {
        class: 'Class 10',
        subject: 'History',
        type: 'mcq',
        difficulty: 'advanced',
        question: 'Which is the largest river in India by volume?',
        options: ['Ganga', 'Brahmaputra', 'Yamuna', 'Godavari'],
        correctAnswer: 'Brahmaputra',
    },
    {
        class: 'Class 7',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'What is the value of 7 × 6?',
        options: ['42', '36', '48', '40'],
        correctAnswer: '42',
    },
    {
        class: 'Class 8',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'Which gas do plants absorb from the atmosphere for photosynthesis?',
        options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
        correctAnswer: 'Carbon dioxide',
    },
    {
        class: 'Class 9',
        subject: 'English',
        type: 'mcq',
        difficulty: 'intermediate',
        question: "Identify the adjective in the sentence: 'She wore a beautiful dress.'",
        options: ['wore', 'beautiful', 'she', 'dress'],
        correctAnswer: 'beautiful',
    },
    {
        class: 'Class 10',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'advanced',
        question: 'What is the solution of the equation: x² - 9 = 0?',
        options: ['x = 3', 'x = -3', 'x = ±3', 'x = 0'],
        correctAnswer: 'x = ±3',
    },
    {
        class: 'Class 6',
        subject: 'History',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'Which is the largest continent by area?',
        options: ['Africa', 'Asia', 'Europe', 'North America'],
        correctAnswer: 'Asia',
    },
    {
        class: 'Class 7',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'Which organ pumps blood throughout the human body?',
        options: ['Lungs', 'Brain', 'Heart', 'Liver'],
        correctAnswer: 'Heart',
    },
    {
        class: 'Class 10',
        subject: 'English',
        type: 'mcq',
        difficulty: 'intermediate',
        question: "Choose the correct synonym of 'Rapid':",
        options: ['Slow', 'Fast', 'Lazy', 'Weak'],
        correctAnswer: 'Fast',
    },
    {
        class: 'Class 8',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'What is the cube of 5?',
        options: ['125', '25', '100', '150'],
        correctAnswer: '125',
    },
    {
        class: 'Class 6',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'Which of the following is a natural fiber?',
        options: ['Nylon', 'Polyester', 'Silk', 'Acrylic'],
        correctAnswer: 'Silk',
    },
    {
        class: 'Class 7',
        subject: 'History',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'What is the name of our galaxy?',
        options: ['Andromeda', 'Milky Way', 'Orion', 'Pegasus'],
        correctAnswer: 'Milky Way',
    },
    {
        class: 'Class 10',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'advanced',
        question: 'Which law explains the relationship between current, voltage, and resistance?',
        options: ['Ohm’s Law', 'Newton’s Law', 'Boyle’s Law', 'Hooke’s Law'],
        correctAnswer: 'Ohm’s Law',
    },
    {
        class: 'Class 9',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'What is the value of sin(90°)?',
        options: ['0', '1', '0.5', 'Undefined'],
        correctAnswer: '1',
    },
    {
        class: 'Class 6',
        subject: 'English',
        type: 'mcq',
        difficulty: 'beginner',
        question: "Which is the noun in this sentence: 'The dog barked loudly.'",
        options: ['barked', 'loudly', 'dog', 'the'],
        correctAnswer: 'dog',
    },
    {
        class: 'Class 7',
        subject: 'Math',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'What is the perimeter of a square with side 5 cm?',
        options: ['10 cm', '20 cm', '25 cm', '15 cm'],
        correctAnswer: '20 cm',
    },
    {
        class: 'Class 8',
        subject: 'History',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'Who wrote the Indian National Anthem?',
        options: ['Mahatma Gandhi', 'Bankim Chandra', 'Rabindranath Tagore', 'Jawaharlal Nehru'],
        correctAnswer: 'Rabindranath Tagore',
    },
    {
        class: 'Class 10',
        subject: 'History',
        type: 'mcq',
        difficulty: 'advanced',
        question: "Which river is called the 'Sorrow of Bengal'?",
        options: ['Ganga', 'Damodar', 'Brahmaputra', 'Hooghly'],
        correctAnswer: 'Damodar',
    },
    {
        class: 'Class 9',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'intermediate',
        question: 'What is the SI unit of force?',
        options: ['Joule', 'Watt', 'Newton', 'Pascal'],
        correctAnswer: 'Newton',
    },
    {
        class: 'Class 8',
        subject: 'English',
        type: 'mcq',
        difficulty: 'intermediate',
        question: "Which figure of speech involves a comparison using 'like' or 'as'?",
        options: ['Metaphor', 'Simile', 'Irony', 'Personification'],
        correctAnswer: 'Simile',
    },
    {
        class: 'Class 7',
        subject: 'Science',
        type: 'mcq',
        difficulty: 'beginner',
        question: 'What do we call animals that eat both plants and animals?',
        options: ['Herbivores', 'Carnivores', 'Omnivores', 'Insectivores'],
        correctAnswer: 'Omnivores',
    },
    {
        class: "Class 9",
        subject: "History",
        type: "mcq",
        difficulty: "intermediate",
        question: "Which latitude is also known as the Tropic of Cancer?",
        options: ["23.5° South", "0°", "66.5° North", "23.5° North"],
        correctAnswer: "23.5° North",
    },
    {
        class: "Class 8",
        subject: "Science",
        type: "mcq",
        difficulty: "intermediate",
        question: "Which organelle is known as the powerhouse of the cell?",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi body"],
        correctAnswer: "Mitochondria",
    },
    {
        class: "Class 7",
        subject: "English",
        type: "mcq",
        difficulty: "beginner",
        question: "Identify the adjective in the sentence: 'She wore a beautiful dress.'",
        options: ["She", "wore", "beautiful", "dress"],
        correctAnswer: "beautiful",
    },
    {
        class: "Class 8",
        subject: "English",
        type: "mcq",
        difficulty: "intermediate",
        question: "What figure of speech is used in: 'Time flies like an arrow'?",
        options: ["Simile", "Metaphor", "Hyperbole", "Personification"],
        correctAnswer: "Simile",
    },
    {
        class: "Class 9",
        subject: "English",
        type: "mcq",
        difficulty: "advanced",
        question: "Which of the following is an example of a complex sentence?",
        options: [
            "He runs fast.",
            "Although it was raining, we went out.",
            "She danced and sang.",
            "Shut the door.",
        ],
        correctAnswer: "Although it was raining, we went out.",
    },
    {
        class: "Class 6",
        subject: "Math",
        type: "mcq",
        difficulty: "beginner",
        question: "What is the place value of 7 in the number 3,742?",
        options: ["7", "70", "700", "7000"],
        correctAnswer: "700",
    }
];

const subjectiveQuestions = [
    {
        class: "Class 10",
        subject: "Math",
        type: "subjective",
        difficulty: "advanced",
        question: "Solve the quadratic equation x² - 5x + 6 = 0 and verify the result using the factorization method.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 6",
        subject: "History",
        type: "subjective",
        difficulty: "beginner",
        question: "Define the term 'continent' and list all the seven continents of the world.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "Explain how to find the area of a triangle and solve using base = 5 cm and height = 8 cm.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "Science",
        type: "subjective",
        difficulty: "intermediate",
        question: "Describe the process of photosynthesis with the help of a neat and labeled diagram.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "English",
        type: "subjective",
        difficulty: "intermediate",
        question: "Write a letter to your school principal requesting a change in library timings.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "Science",
        type: "subjective",
        difficulty: "beginner",
        question: "What is digestion? Describe the role of the stomach in the digestion process.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "History",
        type: "subjective",
        difficulty: "intermediate",
        question: "Who was Mahatma Gandhi? Describe his role in India’s freedom struggle.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 10",
        subject: "English",
        type: "subjective",
        difficulty: "advanced",
        question: "Write an essay on 'The Importance of Time Management' in about 200 words.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "Find the volume of a cube whose side is 6 cm. Explain the formula used.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 6",
        subject: "Science",
        type: "subjective",
        difficulty: "beginner",
        question: "What is a habitat? Explain different types of habitats with examples.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "History",
        type: "subjective",
        difficulty: "beginner",
        question: "Write a short note on the water cycle with a labeled diagram.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 10",
        subject: "Science",
        type: "subjective",
        difficulty: "advanced",
        question: "Differentiate between AC and DC. Give two applications of each.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "State and prove the Pythagoras Theorem with a diagram.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 6",
        subject: "English",
        type: "subjective",
        difficulty: "beginner",
        question: "Write a paragraph on your favorite festival and how you celebrate it.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "What is the difference between simple interest and compound interest? Explain with examples.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "History",
        type: "subjective",
        difficulty: "intermediate",
        question: "What were the causes of the Revolt of 1857? Write any four major causes.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 10",
        subject: "History",
        type: "subjective",
        difficulty: "advanced",
        question: "Describe the major soil types found in India and their characteristics.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "Science",
        type: "subjective",
        difficulty: "intermediate",
        question: "What are Newton’s three laws of motion? Explain with examples.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "English",
        type: "subjective",
        difficulty: "intermediate",
        question: "Explain the difference between active and passive voice with 2 examples each.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "History",
        type: "subjective",
        difficulty: "beginner",
        question: "Who was Ashoka? Mention any three features of his rule.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 6",
        subject: "Math",
        type: "subjective",
        difficulty: "beginner",
        question: "What is an even number? List all even numbers between 10 and 30.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "English",
        type: "subjective",
        difficulty: "intermediate",
        question: "Write a short paragraph describing your favorite book and why you like it.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "Science",
        type: "subjective",
        difficulty: "intermediate",
        question: "Explain the three states of matter with examples and diagrams.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "History",
        type: "subjective",
        difficulty: "intermediate",
        question: "Describe the impact of British rule on the Indian economy.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 10",
        subject: "History",
        type: "subjective",
        difficulty: "advanced",
        question: "What is sustainable development? Discuss with examples from India.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 9",
        subject: "Science",
        type: "subjective",
        difficulty: "advanced",
        question: "Explain the process of photosynthesis with the help of a balanced chemical equation.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 6",
        subject: "English",
        type: "subjective",
        difficulty: "beginner",
        question: "Write a letter to your friend telling them about your recent vacation.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 10",
        subject: "English",
        type: "subjective",
        difficulty: "advanced",
        question: "Discuss the central theme of the poem 'The Road Not Taken' by Robert Frost.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 7",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "Solve: A train travels 240 km in 3 hours. What is its average speed? Show your calculation.",
        options: [],
        correctAnswer: "",
    },
    {
        class: "Class 8",
        subject: "Math",
        type: "subjective",
        difficulty: "intermediate",
        question: "Find the area and perimeter of a rectangle with length 12 cm and breadth 5 cm.",
        options: [],
        correctAnswer: "",
    }
];

const seedQuestions = async () => {
    try {
        await mongoose.connect(MONGO_URI);
        console.log('✅ Connected to MongoDB');
        const allQuestions = await Question.find({});
        console.log(allQuestions.length); // Should show 40, 80, etc.


        // const allQuestions = [...mcqQuestions, ...subjectiveQuestions];
        // await Question.insertMany(allQuestions);

        // console.log(`✅ Seeded ${mcqQuestions.length} MCQ + ${subjectiveQuestions.length} Subjective questions`);
        await mongoose.disconnect();
        console.log('🔌 MongoDB disconnected');
    } catch (error) {
        console.error('❌ Error seeding questions:', error);
        process.exit(1);
    }
};

seedQuestions();
